name: Check Environment Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check for secrets
      run: |
        if [ -n "$FACEBOOK_ACCESS_TOKEN" ]; then
          echo "FACEBOOK_ACCESS_TOKEN is set"
        else
          echo "FACEBOOK_ACCESS_TOKEN is NOT set"
        fi
        
        if [ -n "$NEWSAPI_KEY" ]; then
          echo "NEWSAPI_KEY is set"
        else
          echo "NEWSAPI_KEY is NOT set"
        fi
        
        if [ -n "$GOOGLE_API_KEY" ]; then
          echo "GOOGLE_API_KEY is set"
        else
          echo "GOOGLE_API_KEY is NOT set"
        fi
      env:
        FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }} 